services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./MariaDB
    image: mariadb:inception
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql 
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    build: ./NGINX
    env_file: .env
    ports:
      - "433:433"
    restart: always

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes: 
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: ./WordPress
    depends_on:
      - mariadb
    restart: always
    expose: 
      - "9000"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zbentalh/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind                                
      device: /home/zbentalh/data/mariadb

networks:
  inception:
    name: inception
    driver: bridge